"""Show the source page, then frozen notation at the recorded playback time."""
from pathlib import Path
import json
import numpy as np
import re
import subprocess
import xml.etree.ElementTree as ET
from PIL import Image, ImageDraw, ImageFont

R = Path(__file__).resolve().parents[1]
W, H, FPS, DURATION = 1920, 1080, 24, 64
NS = {'s': 'http://www.w3.org/2000/svg'}


def font(size):
    for path in ['/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf',
                 '/System/Library/Fonts/Supplemental/Times New Roman.ttf']:
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    raise FileNotFoundError('Install DejaVu Serif or Times New Roman')


def mounted(image, label):
    canvas = Image.new('RGB', (W, H), 'white')
    image = image.copy()
    image.thumbnail((1760, 850), Image.Resampling.LANCZOS)
    canvas.paste(image, ((W-image.width)//2, (H-image.height)//2))
    draw = ImageDraw.Draw(canvas)
    draw.text((80, 42), 'Schubert · Quartettsatz, D. 703', fill='black', font=font(28))
    draw.text((80, 1008), label, fill='black', font=font(23))
    return canvas


def score_frames():
    alignment = json.loads((R/'results/playback-alignment.json').read_text())['measures']
    onset = {int(m['label']): m['quarter_onset']*60/168 for m in alignment if m['occurrence']==0}
    frames = []
    number = 1
    for path in sorted((R/'results/notation').glob('*.svg')):
        root = ET.parse(path).getroot()
        raster = Image.open(path.with_suffix('.png')).convert('RGB')
        scale = raster.width/16000
        systems = root.findall('.//s:g[@class="system"]', NS)
        staff_ranges = []
        for system in systems:
            paths = system.findall('.//s:g[@class="staff"]/s:path', NS)
            ys = [float(re.match(r'M[\d.]+ ([\d.]+)', p.attrib['d'])[1]) for p in paths]
            staff_ranges.append(((min(ys)+500)*scale, (max(ys)+500)*scale))
        white_rows = np.all(np.asarray(raster.convert('L')) > 245, axis=1)
        cuts = [0]
        for previous, following in zip(staff_ranges, staff_ranges[1:]):
            candidates = np.flatnonzero(white_rows[int(previous[1])+1:int(following[0])]) + int(previous[1])+1
            assert len(candidates), 'No blank boundary between score systems'
            midpoint = (previous[1]+following[0])/2
            cuts.append(int(candidates[np.argmin(abs(candidates-midpoint))]))
        cuts.append(raster.height)
        for system_index, system in enumerate(systems):
            measures = system.findall('s:g[@class="measure"]', NS)
            if not measures:
                continue
            label = system.find('.//s:g[@class="mNum autogenerated"]', NS)
            if label is not None:
                number = int(''.join(label.itertext()).strip())
            crop = raster.crop((0, cuts[system_index], raster.width, cuts[system_index+1]))
            frame = mounted(crop, 'Audiveris transcription · uncorrected')
            frames.append((onset[number], frame))
            number += len(measures)
        if frames[-1][0] > 56:
            break
    return frames


def main():
    scanpath = R/'build/page-000.png'
    if not scanpath.exists():
        scanpath.parent.mkdir(exist_ok=True)
        subprocess.run(['pdfimages', '-f', '1', '-l', '1', '-png', str(R/'data/scan.pdf'),
                        str(R/'build/page')], check=True)
    scan = Image.open(scanpath).convert('RGB')
    intro = mounted(scan, 'Source · IMSLP04039, p. 1')
    frames = score_frames()
    intro.save(R/'demo/poster.png')
    audio = R/'build/performance.wav'
    if not audio.exists():
        audio = R/'results/performance.mp3'
    cmd = ['ffmpeg','-y','-v','error','-f','rawvideo','-pix_fmt','rgb24','-s',f'{W}x{H}',
           '-r',str(FPS),'-i','-','-i',str(audio),'-filter_complex',
           '[1:a]adelay=8000|8000,atrim=duration=64,afade=t=out:st=60:d=4[a]',
           '-map','0:v','-map','[a]','-c:v','libx264','-preset','fast','-crf','19',
           '-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-t',str(DURATION),
           '-movflags','+faststart',str(R/'demo/clara.mp4')]
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE)
    index = 0
    for i in range(DURATION*FPS):
        time = i/FPS-8
        while index+1 < len(frames) and frames[index+1][0] <= time:
            index += 1
        proc.stdin.write((intro if time < 0 else frames[index][1]).tobytes())
    proc.stdin.close()
    assert proc.wait() == 0

if __name__ == '__main__':
    main()
